#Enumerate
Sirve para recorrer elementos de una lista y tener su indice (la posicion) al mismo tiempo, no es necesario crear variables de contadores manuales.
Por defecto el indice inicia en 0

Permite que sea mas limpio y rapido el codigo.

In [1]:
import pandas as pd
import numpy as np

In [4]:
datos = {
    'sucursal': ['Lima', 'Lima', 'Cusco', 'Cusco', 'Arequipa', 'Lima', np.nan],
    'vendedor': ['Ana', 'Luis', 'Ana', 'Carlos', 'Luis', 'Ana', 'Pedro'],
    'producto': ['Laptop', 'Mouse', 'Laptop', 'Teclado', 'Mouse', 'Monitor', 'Teclado'],
    'ventas_usd': [1200, 50, 1200, 80, 50, 300, 80],
    'cantidad': [1, 2, 1, 3, 2, 1, 3]
}

df = pd.DataFrame(datos)
display(df)

,sucursal,vendedor,producto,ventas_usd,cantidad
0,Lima,Ana,Laptop,1200,1
1,Lima,Luis,Mouse,50,2
2,Cusco,Ana,Laptop,1200,1
3,Cusco,Carlos,Teclado,80,3
4,Arequipa,Luis,Mouse,50,2
5,Lima,Ana,Monitor,300,1
6,NaN,Pedro,Teclado,80,3


In [5]:
sucursales = ['Lima', 'Cusco', 'Arequipa']
for sucursal in sucursales:
    print(sucursal)

Lima
Cusco
Arequipa


In [6]:
for sucursal in enumerate(sucursales):
    print(sucursal)

(0, 'Lima')
(1, 'Cusco')
(2, 'Arequipa')


In [9]:
for indice, sucursal in enumerate(sucursales):
    print(f'Sucursal #{indice+1}: {sucursal}')

Sucursal #1: Lima
Sucursal #2: Cusco
Sucursal #3: Arequipa


In [12]:
for ciudad in enumerate(sucursales, start=2):
  print(ciudad)

(2, 'Lima')
(3, 'Cusco')
(4, 'Arequipa')


In [14]:
for posicion, ciudad in enumerate(sucursales, start=1):
  print(f'Sucursal #{posicion}: {sucursal}')

Sucursal #1: Arequipa
Sucursal #2: Arequipa
Sucursal #3: Arequipa


#groupby (Excel: Tabla dinamica pero sin ser dinamica)
SPLIT: Dividir la tabla originales en pequeños grupos basados en los valores de una o mas columnas.

APPLY: Aplicamos una funcion de agregacion, es una funcion matematica que se le aplica a cada grupo de manera independiente.

COMBINE: Junta todos los resutlados en una tabla resumida.

Te va permitir responder preguntas de negocio.

Metodos:

*   .sum(): suma
*   .mean(): promedio
*   .count(): recuento
*   .agg(): te permite utilizar mas de una funcion de agregacion

In [ ]:
datos = {
    'sucursal': ['Lima', 'Lima', 'Cusco', 'Cusco', 'Arequipa', 'Lima', np.nan],
    'vendedor': ['Ana', 'Luis', 'Ana', 'Carlos', 'Luis', 'Ana', 'Pedro'],
    'producto': ['Laptop', 'Mouse', 'Laptop', 'Teclado', 'Mouse', 'Monitor', 'Teclado'],
    'ventas_usd': [1200, 50, 1200, 80, 50, 300, 80],
    'cantidad': [1, 2, 1, 3, 2, 1, 3]
}

df = pd.DataFrame(datos)
display(df)

In [18]:
ventas_por_sucursal = df.groupby('sucursal').sum()

print(ventas_por_sucursal)

            vendedor            producto  ventas_usd  cantidad
sucursal                                                      
Arequipa        Luis               Mouse          50         2
Cusco      AnaCarlos       LaptopTeclado        1280         4
Lima      AnaLuisAna  LaptopMouseMonitor        1550         4


In [28]:
ventas_por_sucursal_isnum = df.groupby('sucursal').sum(numeric_only=True)

print(ventas_por_sucursal_isnum)

          ventas_usd  cantidad
sucursal                      
Arequipa          50         2
Cusco           1280         4
Lima            1550         4


In [22]:
df.groupby(['sucursal', 'vendedor']).agg({
                                        'ventas_usd': 'sum',
                                        'cantidad': ['count','sum']
                                        })


ventas_usd cantidad    
                         sum    count sum
sucursal vendedor                        
Arequipa Luis             50        1   2
Cusco    Ana            1200        1   1
         Carlos           80        1   3
Lima     Ana            1500        2   2
         Luis             50        1   2

In [23]:
ventas_por_sucursal = df.groupby('sucursal')['ventas_usd'].sum()

print(ventas_por_sucursal)

sucursal
Arequipa      50
Cusco       1280
Lima        1550
Name: ventas_usd, dtype: int64


In [24]:
ventas_por_sucursal_agg = df.groupby('sucursal').agg({'ventas_usd':'sum'})

print(ventas_por_sucursal_agg)

          ventas_usd
sucursal            
Arequipa          50
Cusco           1280
Lima            1550


In [26]:
report_conNa = df.groupby(
    ['sucursal','vendedor','producto'],
    dropna=False
).agg({'ventas_usd':'sum'})

print(report_conNa)

                            ventas_usd
sucursal vendedor producto            
Arequipa Luis     Mouse             50
Cusco    Ana      Laptop          1200
         Carlos   Teclado           80
Lima     Ana      Laptop          1200
                  Monitor          300
         Luis     Mouse             50
NaN      Pedro    Teclado           80


In [27]:
report_conNa = df.groupby(
    ['sucursal','vendedor','producto'],
    dropna=False,
    as_index=False
).agg({'ventas_usd':'sum'})

print(report_conNa)

   sucursal vendedor producto  ventas_usd
0  Arequipa     Luis    Mouse          50
1     Cusco      Ana   Laptop        1200
2     Cusco   Carlos  Teclado          80
3      Lima      Ana   Laptop        1200
4      Lima      Ana  Monitor         300
5      Lima     Luis    Mouse          50
6       NaN    Pedro  Teclado          80


#Enumerate con groupby

In [30]:
list_gb_ciudades = df.groupby('sucursal')

for ciudad in enumerate(list_gb_ciudades):
  print(ciudad)

(0, ('Arequipa',    sucursal vendedor producto  ventas_usd  cantidad
4  Arequipa     Luis    Mouse          50         2))
(1, ('Cusco',   sucursal vendedor producto  ventas_usd  cantidad
2    Cusco      Ana   Laptop        1200         1
3    Cusco   Carlos  Teclado          80         3))
(2, ('Lima',   sucursal vendedor producto  ventas_usd  cantidad
0     Lima      Ana   Laptop        1200         1
1     Lima     Luis    Mouse          50         2
5     Lima      Ana  Monitor         300         1))


In [32]:
for indice,(nombre_ciudad,sub_df) in enumerate(list_gb_ciudades):
  print(f'\nCiudad #{indice+1}: {nombre_ciudad}')
  print(sub_df[['vendedor','ventas_usd']])


Ciudad #1: Arequipa
  vendedor  ventas_usd
4     Luis          50

Ciudad #2: Cusco
  vendedor  ventas_usd
2      Ana        1200
3   Carlos          80

Ciudad #3: Lima
  vendedor  ventas_usd
0      Ana        1200
1     Luis          50
5      Ana         300


# np.where
Es una funcion de la libreria Numpy que se comporta como un condicional para un arreglo o lista.

In [33]:
import pandas as pd
import numpy as np

In [34]:
datos = {
    'estudiantes':['Ana','Luis','Carlos','Maria','Pedro','Sofia'],
    'nota': [18,10,15,8,np.nan,20],
    'asistencias': [90,85,40,50,10,100],
    'edad':[22,17,25,16,21,20]
}
df = pd.DataFrame(datos)

In [35]:
display(df)

,estudiantes,nota,asistencias,edad
0,Ana,18.0,90,22
1,Luis,10.0,85,17
2,Carlos,15.0,40,25
3,Maria,8.0,50,16
4,Pedro,NaN,10,21
5,Sofia,20.0,100,20


In [37]:
df['estado'] = np.where(
    df['nota']>= 11,  # Condicion
    'Aprobado',       # En caso sea verdadero la condicion
    'Reprobado'       # En caso sea falsa la condicion
)

In [38]:
display(df)

,estudiantes,nota,asistencias,edad,estado
0,Ana,18.0,90,22,Aprobado
1,Luis,10.0,85,17,Reprobado
2,Carlos,15.0,40,25,Aprobado
3,Maria,8.0,50,16,Reprobado
4,Pedro,NaN,10,21,Reprobado
5,Sofia,20.0,100,20,Aprobado


In [41]:
df['beca'] = np.where(
    (df['edad']>= 11) & (df['nota']>=18),  # Condicion mas de una or --> |
    'Otorgado',       # En caso sea verdadero la condicion
    'Denegado'       # En caso sea falsa la condicion
)

In [42]:
display(df)

,estudiantes,nota,asistencias,edad,estado,beca
0,Ana,18.0,90,22,Aprobado,Otorgado
1,Luis,10.0,85,17,Reprobado,Denegado
2,Carlos,15.0,40,25,Aprobado,Denegado
3,Maria,8.0,50,16,Reprobado,Denegado
4,Pedro,NaN,10,21,Reprobado,Denegado
5,Sofia,20.0,100,20,Aprobado,Otorgado


In [44]:
df['rendimiento'] = np.where(df['nota']>17, 'Sobresaliente',
         np.where(df['nota']>=11, 'Regular', 'Deficiente')
         )

In [45]:
display(df)

,estudiantes,nota,asistencias,edad,estado,beca,rendimiento
0,Ana,18.0,90,22,Aprobado,Otorgado,Sobresaliente
1,Luis,10.0,85,17,Reprobado,Denegado,Deficiente
2,Carlos,15.0,40,25,Aprobado,Denegado,Regular
3,Maria,8.0,50,16,Reprobado,Denegado,Deficiente
4,Pedro,NaN,10,21,Reprobado,Denegado,Deficiente
5,Sofia,20.0,100,20,Aprobado,Otorgado,Sobresaliente


In [47]:
df['nota_final'] = np.where(
    df['asistencias'] < 50,
    df['nota']*0.8,
    df['nota']
)

In [48]:
display(df)

,estudiantes,nota,asistencias,edad,estado,beca,rendimiento,nota_final
0,Ana,18.0,90,22,Aprobado,Otorgado,Sobresaliente,18.0
1,Luis,10.0,85,17,Reprobado,Denegado,Deficiente,10.0
2,Carlos,15.0,40,25,Aprobado,Denegado,Regular,12.0
3,Maria,8.0,50,16,Reprobado,Denegado,Deficiente,8.0
4,Pedro,NaN,10,21,Reprobado,Denegado,Deficiente,NaN
5,Sofia,20.0,100,20,Aprobado,Otorgado,Sobresaliente,20.0


In [49]:
array = df['nota'].values

In [50]:
array

array([18., 10., 15.,  8., nan, 20.])

In [54]:
np.where(np.isnan(array))[0]

array([4])

In [55]:
np.where(np.isnan(df['nota']))

(array([4]),)